### ISSUE TITLE
File Uploaded via add-notice API Becomes Corrupted and Unreadable

### ISSUE THREAD

**Issue by VivekCodees** [joplangmaring/AIDS#14]
**Description:**
When uploading a file through the add-notice API, the file is successfully uploaded and saved. However, the uploaded file becomes unusable or unreadable. This issue prevents the file from being processed or accessed properly.

**Steps to Reproduce:**
1. Create a post request on the add-notice API to upload a file.
2. Pass the required parameters and attach a file to the request.
3. Verify the file upload is completed successfully and file is saved in /public/temp.
4. Try to open the uploaded file.

**Expected Behavior:**
The file should be uploaded, readable, and usable.
**Actual Behavior:**
The file is uploaded but becomes corrupted or unreadable.

Kindly provide a fix for this issue at the earliest

**Comment by webgaurav02** [comment]
**Fix Summary:**
The issue with unreadable files after upload was fixed by modifying the file upload process. The file is now passed as a **base64 encoded** string in the request payload, along with an additional `fileExtension` attribute. This `fileExtension` is crucial as it helps to:

- Retain the original file extension when saving the file in the `/public/temp` directory.
- Ensure that the file is stored correctly, making it readable and usable after upload.
- Save the file path, including the correct extension, in the MongoDB collection to facilitate proper file access and processing.
- This fix ensures that uploaded files are correctly stored and accessible without corruption.


Additionally, I have created and optimised the frontend code for the admin dashboard. This includes creating the `add-notice` page, placement of the sidebar on the `layout.js` file, extracting the file extension on the client-side and passing it alongside the base64 file, ensuring smooth communication between the frontend and backend.


<img width="1440" alt="Screenshot 2024-12-02 at 12 40 12 AM" src="https://github.com/user-attachments/assets/abb2a127-c4e0-420c-903c-33798ff89054">
<img width="1440" alt="Screenshot 2024-12-02 at 12 40 20 AM" src="https://github.com/user-attachments/assets/5722df57-a727-4406-b95d-c30ddb097a92">
